# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_windows/base_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1429, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1150, 20, 191, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 570, 191, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(230, 570, 51, 31))
        self.label_error.setAutoFillBackground(False)
        self.label_error.setObjectName("label_error")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 166, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(20, 80, 67, 17))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 570, 191, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.box_area_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.box_area_1.setObjectName("box_area_1")
        self.verticalLayout.addWidget(self.box_area_1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 20, 160, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.box_point_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.box_point_1.setObjectName("box_point_1")
        self.verticalLayout_2.addWidget(self.box_point_1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(410, 20, 160, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.box_file_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.box_file_1.setObjectName("box_file_1")
        self.verticalLayout_3.addWidget(self.box_file_1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(580, 20, 160, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.box_sheet_1 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.box_sheet_1.setObjectName("box_sheet_1")
        self.verticalLayout_4.addWidget(self.box_sheet_1)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 210, 81, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(30, 277, 81, 61))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(30, 347, 81, 55))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(30, 420, 81, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_8.addWidget(self.lineEdit_5)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(180, 210, 81, 51))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_11.addWidget(self.lineEdit_6)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(180, 280, 81, 55))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_17.addWidget(self.lineEdit_7)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(180, 350, 81, 55))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_18.addWidget(self.lineEdit_8)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(180, 420, 82, 55))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_19.addWidget(self.label_11)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_19.addWidget(self.lineEdit_9)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(330, 210, 81, 51))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_20.addWidget(self.label_12)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_20.addWidget(self.lineEdit_10)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(330, 280, 81, 65))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_21.addWidget(self.label_13)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_14)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_21.addWidget(self.lineEdit_11)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(480, 210, 81, 51))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_22.addWidget(self.label_17)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_22.addWidget(self.lineEdit_12)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 165, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(480, 280, 81, 51))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_23.addWidget(self.label_18)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_23.addWidget(self.lineEdit_13)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(480, 350, 81, 55))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_24.addWidget(self.label_19)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_24.addWidget(self.lineEdit_14)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(630, 210, 81, 51))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_25.addWidget(self.label_20)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_25.addWidget(self.lineEdit_15)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(630, 280, 81, 51))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_26.addWidget(self.label_22)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_26.addWidget(self.lineEdit_16)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(330, 160, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(480, 165, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(630, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(780, 160, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(630, 350, 81, 55))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_27.addWidget(self.label_23)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_27.addWidget(self.lineEdit_17)
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(780, 210, 83, 51))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_28.addWidget(self.label_24)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.verticalLayoutWidget_21)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_28.addWidget(self.lineEdit_18)
        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(780, 280, 81, 51))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_22)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_29.addWidget(self.label_25)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_29.addWidget(self.lineEdit_19)
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(930, 210, 81, 51))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(7)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_30.addWidget(self.label_30)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.verticalLayoutWidget_23)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_30.addWidget(self.lineEdit_20)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(930, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(1110, 70, 291, 531))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.box_area_1, self.box_point_1)
        MainWindow.setTabOrder(self.box_point_1, self.box_file_1)
        MainWindow.setTabOrder(self.box_file_1, self.box_sheet_1)
        MainWindow.setTabOrder(self.box_sheet_1, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.lineEdit_14)
        MainWindow.setTabOrder(self.lineEdit_14, self.lineEdit_15)
        MainWindow.setTabOrder(self.lineEdit_15, self.lineEdit_16)
        MainWindow.setTabOrder(self.lineEdit_16, self.lineEdit_17)
        MainWindow.setTabOrder(self.lineEdit_17, self.lineEdit_18)
        MainWindow.setTabOrder(self.lineEdit_18, self.lineEdit_19)
        MainWindow.setTabOrder(self.lineEdit_19, self.lineEdit_20)
        MainWindow.setTabOrder(self.lineEdit_20, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.listView)
        MainWindow.setTabOrder(self.listView, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "print( ui.__dict__ )"))
        self.pushButton_2.setText(_translate("MainWindow", "Сохранить"))
        self.label_error.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ef2929;\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Количество\n"
"выездов"))
        self.pushButton_3.setText(_translate("MainWindow", "Очистить поля ввода"))
        self.label_21.setText(_translate("MainWindow", "Район:"))
        self.label_29.setText(_translate("MainWindow", "Подразделение:"))
        self.label_15.setText(_translate("MainWindow", "Имя файла:"))
        self.label_16.setText(_translate("MainWindow", "Название вкладки:"))
        self.label_3.setText(_translate("MainWindow", "На тушение"))
        self.label_4.setText(_translate("MainWindow", "На проведение\n"
"АСР"))
        self.label_5.setText(_translate("MainWindow", "Ложные"))
        self.label_6.setText(_translate("MainWindow", "На учения"))
        self.label_7.setText(_translate("MainWindow", "Всего пожаров"))
        self.label_9.setText(_translate("MainWindow", "В жил. секторе"))
        self.label_10.setText(_translate("MainWindow", "В произ./админ.\n"
"зданиях"))
        self.label_11.setText(_translate("MainWindow", "На прочих\n"
"объектах"))
        self.label_12.setText(_translate("MainWindow", "Человек"))
        self.label_13.setText(_translate("MainWindow", "Матер-ных\n"
"ценностей\n"
"(тыс. руб)"))
        self.label_17.setText(_translate("MainWindow", "Всего человек"))
        self.label_8.setText(_translate("MainWindow", "Количество\n"
"пожаров"))
        self.label_18.setText(_translate("MainWindow", "Детей"))
        self.label_19.setText(_translate("MainWindow", "Работников\n"
"ПС"))
        self.label_20.setText(_translate("MainWindow", "Всего человек"))
        self.label_22.setText(_translate("MainWindow", "Детей"))
        self.label_14.setText(_translate("MainWindow", "Спасено"))
        self.label_26.setText(_translate("MainWindow", "Количество\n"
"погибших"))
        self.label_27.setText(_translate("MainWindow", "Количество\n"
"травмированных"))
        self.label_28.setText(_translate("MainWindow", "Силы и\n"
"стредства"))
        self.label_23.setText(_translate("MainWindow", "Работников\n"
"ПС"))
        self.label_24.setText(_translate("MainWindow", "Личного состава"))
        self.label_25.setText(_translate("MainWindow", "Ед. техники"))
        self.label_31.setText(_translate("MainWindow", "Среднее время\n"
"реагирования"))
